import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout";
import GameProvider from "../components/GameProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="w-full bg-green-dark border-b border-green">
          <div className="max-w-7xl mx-auto px-4 py-4">
            <h1 className="text-2xl font-bold tracking-wider text-green-light">MY CHESS COACH</h1>
          </div>
        </header>
        <main className="px-4 py-6">
          <GameProvider>
            <ClientLayout />
          </GameProvider>
        </main>
      </body>
    </html>
  );
}
